In [1]:
import pandas as pd
import seaborn as sb
import numpy as np
import matplotlib.pyplot as plt
import json
import re
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
# display the dataframe head

In [2]:
car = pd.read_json('scout_car.json', lines=True)

In [3]:
car1=car.copy()

In [5]:
car1.shape

(15919, 54)

In [8]:
car1.dtypes

url                              object
make_model                       object
short_description                object
body_type                        object
price                            object
vat                              object
km                               object
registration                     object
prev_owner                       object
kW                               object
hp                               object
Type                             object
Previous_Owners                  object
Next_Inspection                  object
Inspection_new                   object
Warranty                         object
Full_Service                     object
Non-smoking_Vehicle              object
null                             object
Make                             object
Model                            object
Offer_Number                     object
First_Registration               object
Body_Color                       object
Paint_Type                       object
Body_Color_Original              object
Upholstery                       object
Body                             object
Nr._of_Doors                     object
Nr._of_Seats                     object
Model_Code                       object
Gearing_Type                     object
Displacement                     object
Cylinders                        object
Weight                           object
Drive_chain                      object
Fuel                             object
Consumption                      object
CO2_Emission                     object
Emission_Class                   object
\nComfort_&_Convenience\n        object
\nEntertainment_&_Media\n        object
\nExtras\n                       object
\nSafety_&_Security\n            object
description                      object
Emission_Label                   object
Gears                            object
Country_version                  object
Electricity_consumption          object
Last_Service_Date                object
Other_Fuel_Types                 object
Availability                     object
Last_Timing_Belt_Service_Date    object
Available_from                   object
dtype: object

In [ ]:
car1

In [61]:
car1.head()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous_Owners,Next_Inspection,Inspection_new,Warranty,Full_Service,Non-smoking_Vehicle,null,Make,Model,Offer_Number,First_Registration,Body_Color,Paint_Type,Body_Color_Original,Upholstery,Body,Nr._of_Doors,Nr._of_Seats,Model_Code,Gearing_Type,Displacement,Cylinders,Weight,Drive_chain,Fuel,Consumption,CO2_Emission,Emission_Class,\nComfort_&_Convenience\n,\nEntertainment_&_Media\n,\nExtras\n,\nSafety_&_Security\n,description,Emission_Label,Gears,Country_version,Electricity_consumption,Last_Service_Date,Other_Fuel_Types,Availability,Last_Timing_Belt_Service_Date,Available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,VAT deductible,"56,013 km",01/2016,2 previous owners,NaN,66 kW,"[, Used, , Diesel (Particulate Filter)]",\n2\n,"[\n06/2021\n, \n99 g CO2/km (comb)\n]","[\nYes\n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]","[\n, \n]",[],\nAudi\n,"[\n, A1, \n]",[\nLR-062483\n],"[\n, 2016, \n]","[\n, Black, \n]",[\nMetallic\n],[\nMythosschwarz\n],"[\nCloth, Black\n]","[\n, Sedans, \n]",[\n5\n],[\n5\n],[\n0588/BDF\n],"[\n, Automatic, \n]","[\n1,422 cc\n]",[\n3\n],"[\n1,220 kg\n]",[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, Hands-free equipment, On-board com...","[Alloy wheels, Catalytic Converter, Voice Cont...","[ABS, Central door lock, Daytime running light...","[\n, Sicherheit:, , Deaktivierung f√ºr Beifahr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.8 TFSI sport,Sedans,14500,Price negotiable,"80,000 km",03/2017,None,NaN,141 kW,"[, Used, , Gasoline]",NaN,NaN,NaN,NaN,NaN,NaN,[],\nAudi\n,"[\n, A1, \n]",NaN,"[\n, 2017, \n]","[\n, Red, \n]",NaN,NaN,"[\nCloth, Grey\n]","[\n, Sedans, \n]",[\n3\n],[\n4\n],[\n0588/BCY\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,255 kg\n]",[\nfront\n],"[\n, Gasoline, \n]","[[5.6 l/100 km (comb)], [7.1 l/100 km (city)],...",[\n129 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...","[Bluetooth, Hands-free equipment, On-board com...","[Alloy wheels, Sport seats, Sport suspension, ...","[ABS, Central door lock, Central door lock wit...",[\nLangstreckenfahrzeug daher die hohe Kilomet...,[\n4 (Green)\n],[\n7\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,VAT deductible,"83,450 km",02/2016,1 previous owner,NaN,85 kW,"[, Used, , Diesel (Particulate Filter)]",\n1\n,NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]",NaN,NaN,[],\nAudi\n,"[\n, A1, \n]",[\nAM-95365\n],"[\n, 2016, \n]","[\n, Black, \n]",[\nMetallic\n],[\nmythosschwarz metallic\n],"[\nCloth, Black\n]","[\n, Sedans, \n]",[\n4\n],[\n4\n],NaN,"[\n, Automatic, \n]","[\n1,598 cc\n]",NaN,NaN,[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[3.8 l/100 km (comb)], [4.4 l/100 km (city)],...",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Cruise control, Electrical ...","[MP3, On-board computer]","[Alloy wheels, Voice Control]","[ABS, Central door lock, Daytime running light...","[\n, Fahrzeug-Nummer: AM-95365, , Ehem. UPE 2...",[\n4 (Green)\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.autoscout24.com//offers/audi-a1-1-...,Audi A1,1.4 TDi Design S tronic,Sedans,14500,None,"73,000 km",08/2016,1 previous owner,NaN,66 kW,"[, Used, , Diesel (Particulate Filter)]",\n1\n,NaN,NaN,NaN,"[\n, \n, \n99 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]",[],\nAudi\n,"[\n, A1, \n]",NaN,"[\n, 2016, \n]","[\n, Brown, \n]",[\nMetallic\n],NaN,NaN,"[\n, Sedans, \n]",[\n3\n],[\n4\n],NaN,"[\n, Automatic, \n]","[\n1,422 cc\n]",[\n3\n],"[\n1,195 kg\n]",NaN,"[\n, Diesel (Particulate Filter), \n]","[[3.8 l/100 km (comb)], [4.3 l/100 km (city)],...",[\n99 g CO2/km (comb)\n],[\nEuro 6\n],"[Air suspension, Armrest, Auxiliary heating, E...","[Bluetooth, CD player, Hands-free equipment, M...","[Alloy wheels, Sport seats, Voice Control]","[ABS, Alarm system, Central door lock with rem...","[\nAudi A1: , - 1e eigenaar , - Perfecte staat...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.autoscout24.com//offers/audi-a1-sp...,Audi A1,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,"16,200 km",05/2016,1 previous owner,NaN,66 kW,"[, Used, , Diesel (Particulate Filter)]",\n1\n,NaN,"[\nYes\n, \n109 g CO2/km (comb)\n]","[\n, \n, \nEuro 6\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]",[],\nAudi\n,"[\n, A1, \n]",[\nC1626\n],"[\n, 2016, \n]","[\n, Black, \n]",[\nMetallic\n],[\nMythosschwarz Metallic\n],"[\nCloth, Black\n]","[\n, Sedans, \n]",[\n5\n],[\n5\n],[\n0588/BDF\n],"[\n, Automatic, \n]","[\n1,422 cc\n]",[\n3\n],NaN,[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[4.1 l/100 km (comb)], [4.6 l/100 km (city)],...",[\n109 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, CD player, Hands-free equipment, M...","[Alloy wheels, Sport package, Sport suspension...","[ABS, Central door lock, Driver-side airbag, E...","[\n, Technik & Sicherheit:, Xenon plus, Klimaa...",NaN,NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
car1.km=car1.km.str.strip("km")
car1.km=car1.km.replace("-",0,regex=True)
car1.km=car1.km.replace(",","",regex=True)
car1.km = car1.km.astype("int64")

In [140]:
car1.tail()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous Owners,Next Inspection,Inspection new,Warranty,Full Service,Non-smoking Vehicle,null,Make,Model,Offer Number,First Registration,Body Color,Paint Type,Body Color Original,Upholstery,Body,Nr. of Doors,Nr. of Seats,Model Code,Gearing Type,Displacement,Cylinders,Weight,Drive chain,Fuel,Consumption,CO2 Emission,Emission Class,\nComfort & Convenience\n,\nEntertainment & Media\n,\nExtras\n,\nSafety & Security\n,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,147 kW,"[, New, , Diesel (Particulate Filter)]",NaN,NaN,NaN,\n24 months\n,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\n10988301\n],NaN,"[\n, Grey, \n]",[\nMetallic\n],[\nGrigio scuro\n],NaN,"[\n, Van, \n]",[\n5\n],[\n5\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],"[\n1,758 kg\n]",[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],NaN,"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Hands-free equipmen...","[Alloy wheels, Touch screen]","[ABS, Central door lock, Central door lock wit...",[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,165 kW,"[, Used, , Super 95 / Super Plus 98 (Particula...","[\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...","[\n01/2022\n, \n168 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]",NaN,"[\n, \n, \n4 (Green)\n]",[],\nRenault\n,"[\n, Espace, \n]",[\n507370_3223\n],"[\n, 2019, \n]","[\n, Grey, \n]",[\nMetallic\n],[\nStahl-Grau Metallic\n],[\nCloth\n],"[\n, Van, \n]",[\n5\n],[\n5\n],[\n0000/000\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,708 kg\n]",[\nfront\n],"[\n, Super 95 / Super Plus 98 (Particulate Fil...","[\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (ci...",[\n168 g CO2/km (comb)\n],NaN,"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Hands-free equipmen...","[Alloy wheels, Touch screen, Voice Control]","[ABS, Adaptive Cruise Control, Blind spot moni...","[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,146 kW,"[, Pre-registered, , Diesel]","[\n1\n, \n139 g CO2/km (comb)\n]",NaN,"[\nYes\n, \nEuro 6d-TEMP\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]","[\n, \n]",[],\nRenault\n,"[\n, Espace, \n]",[\nEspace16\n],"[\n, 2019, \n]","[\n, White, \n]",NaN,[\narktis-wei√ü\n],"[\nFull leather, Black\n]","[\n, Van, \n]",[\n5\n],[\n7\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],NaN,[\nfront\n],"[\n, Diesel, \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, Hands-free equipment, On-board com...",[Alloy wheels],"[ABS, Adaptive Cruise Control, Blind spot moni...","[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,147 kW,"[, Pre-registered, , Diesel]",NaN,NaN,NaN,\n,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\n2691331\n],"[\n, 2019, \n]","[\n, Grey, \n]",NaN,[\nGrigio\n],[\nPart leather\n],"[\n, Van, \n]",[\n5\n],[\n7\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],"[\n1,758 kg\n]",[\nfront\n],"[\n, Diesel, \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Radio, USB]","[Alloy wheels, Touch screen]","[ABS, Blind spot monitor, Driver-side airbag, ...","[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,165 kW,"[, Demonstration, , Super 95]",\n1\n,NaN,"[\nYes\n, \n153 g CO2/km (comb)\n]",NaN,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\nRe_30000008029\n],"[\n, 2019, \n]","[\n, Grey, \n]",[\nMetallic\n],[\nTitanium-Grau Metallic\n],"[\nFull leather, Brown\n]","[\n, Van, \n]",[\n5\n],[\n5\n],[\n3333/BHJ\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,685 kg\n]",[\n4WD\n],"[\n, Super 95, \n]","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],...",[\n153 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...",[USB],"[Alloy wheels, Touch screen]","[ABS, Blind spot monitor, Daytime running ligh...","[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
car1=car.copy()
car1.columns = car1.columns.str.replace(' ', '_')
car1 = car1.astype(str)

In [196]:
car1.dtypes

for column in car1:
        #print(car[column].iloc[:10])
    if column=="make_model":
        car1[column]=car1[column].str.extract(r'(.*\w{3,15})')
    elif column=="vat":
        car1[column]=car1[column].str.extract(r'(\w+$)')
    elif column=="km":
        car1[column]=car1[column].str.replace(",","")
    elif column=="hp":
        car1[column]=car1[column].str.extract(r'(.*\d)')
    elif column=="Warranty":
        car1[column]=car1[column].str.extract(r'(\d+)')
    elif column=="Offer_Number":
        car1[column]=car1[column].str.extract(r'(\d+)')
    elif column=="First_Registration":
        car1[column]=car1[column].str.extract(r'(\d+)')
    elif column=="Body_Color":
        car1[column]=car1[column].str.extract(r'(\w{3,15})')
    elif column=="Paint_Type":
        car1[column]=car1[column].str.extract(r'(\w{3,15})')
    elif column=="Nr._of_Doors":
        car1[column]=car1[column].str.extract(r'(\d+)')
    elif column=="Nr._of_Seats":
        car1[column]=car1[column].str.extract(r'(\d+)')
    
    #elif column=="Type":
        #car1[column]=car1[column].str.extract(r'(?:Diesel)',expand=True)

In [197]:
car1.head()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous_Owners,Next_Inspection,Inspection_new,Warranty,Full_Service,Non-smoking_Vehicle,null,Make,Model,Offer_Number,First_Registration,Body_Color,Paint_Type,Body_Color_Original,Upholstery,Body,Nr._of_Doors,Nr._of_Seats,Model_Code,Gearing_Type,Displacement,Cylinders,Weight,Drive_chain,Fuel,Consumption,CO2_Emission,Emission_Class,\nComfort_&_Convenience\n,\nEntertainment_&_Media\n,\nExtras\n,\nSafety_&_Security\n,description,Emission_Label,Gears,Country_version,Electricity_consumption,Last_Service_Date,Other_Fuel_Types,Availability,Last_Timing_Belt_Service_Date,Available_from
0,https://www.autoscout24.com//offers/audi-a1-sp...,Audi,Sportback 1.4 TDI S-tronic Xenon Navi Klima,Sedans,15770,deductible,56013 km,01/2016,2 previous owners,nan,66,"['', 'Used', '', 'Diesel (Particulate Filter)']",\n2\n,"['\n06/2021\n', '\n99 g CO2/km (comb)\n']","['\nYes\n', '\nEuro 6\n']",4,"['\n', '\n']","['\n', '\n']",[],\nAudi\n,"['\n', 'A1', '\n']",062483,2016,Black,nMetallic,['\nMythosschwarz\n'],"['\nCloth, Black\n']","['\n', 'Sedans', '\n']",5,5,['\n0588/BDF\n'],"['\n', 'Automatic', '\n']","['\n1,422 cc\n']",['\n3\n'],"['\n1,220 kg\n']",['\nfront\n'],"['\n', 'Diesel (Particulate Filter)', '\n']","[['3.8 l/100 km (comb)'], ['4.3 l/100 km (city...",['\n99 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air conditioning', 'Armrest', 'Automatic cli...","['Bluetooth', 'Hands-free equipment', 'On-boar...","['Alloy wheels', 'Catalytic Converter', 'Voice...","['ABS', 'Central door lock', 'Daytime running ...","['\n', 'Sicherheit:', ' ', 'Deaktivierung f√ºr ...",nan,nan,nan,nan,nan,nan,nan,nan,nan
1,https://www.autoscout24.com//offers/audi-a1-1-...,Audi,1.8 TFSI sport,Sedans,14500,negotiable,80000 km,03/2017,None,nan,141,"['', 'Used', '', 'Gasoline']",nan,nan,nan,NaN,nan,nan,[],\nAudi\n,"['\n', 'A1', '\n']",NaN,2017,Red,nan,nan,"['\nCloth, Grey\n']","['\n', 'Sedans', '\n']",3,4,['\n0588/BCY\n'],"['\n', 'Automatic', '\n']","['\n1,798 cc\n']",['\n4\n'],"['\n1,255 kg\n']",['\nfront\n'],"['\n', 'Gasoline', '\n']","[['5.6 l/100 km (comb)'], ['7.1 l/100 km (city...",['\n129 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air conditioning', 'Automatic climate contro...","['Bluetooth', 'Hands-free equipment', 'On-boar...","['Alloy wheels', 'Sport seats', 'Sport suspens...","['ABS', 'Central door lock', 'Central door loc...",['\nLangstreckenfahrzeug daher die hohe Kilome...,['\n4 (Green)\n'],['\n7\n'],nan,nan,nan,nan,nan,nan,nan
2,https://www.autoscout24.com//offers/audi-a1-sp...,Audi,Sportback 1.6 TDI S tronic Einparkhilfe plus+m...,Sedans,14640,deductible,83450 km,02/2016,1 previous owner,nan,85,"['', 'Used', '', 'Diesel (Particulate Filter)']",\n1\n,nan,nan,99,nan,nan,[],\nAudi\n,"['\n', 'A1', '\n']",95365,2016,Black,nMetallic,['\nmythosschwarz metallic\n'],"['\nCloth, Black\n']","['\n', 'Sedans', '\n']",4,4,nan,"['\n', 'Automatic', '\n']","['\n1,598 cc\n']",nan,nan,['\nfront\n'],"['\n', 'Diesel (Particulate Filter)', '\n']","[['3.8 l/100 km (comb)'], ['4.4 l/100 km (city...",['\n99 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air conditioning', 'Cruise control', 'Electr...","['MP3', 'On-board computer']","['Alloy wheels', 'Voice Control']","['ABS', 'Central door lock', 'Daytime running ...","['\n', 'Fahrzeug-Nummer: AM-95365', ' ', 'Ehem...",['\n4 (Green)\n'],nan,nan,nan,nan,nan,nan,nan,nan
3,https://www.autoscout24.com//offers/audi-a1-1-...,Audi,1.4 TDi Design S tronic,Sedans,14500,None,73000 km,08/2016,1 previous owner,nan,66,"['', 'Used', '', 'Diesel (Particulate Filter)']",\n1\n,nan,nan,NaN,"['\n', '\n', '\n99 g CO2/km (comb)\n']","['\n', '\n', '\nEuro 6\n']",[],\nAudi\n,"['\n', 'A1', '\n']",NaN,2016,Brown,nMetallic,nan,nan,"['\n', 'Sedans', '\n']",3,4,nan,"['\n', 'Automatic', '\n']","['\n1,422 cc\n']",['\n3\n'],"['\n1,195 kg\n']",nan,"['\n', 'Diesel (Particulate Filter)', '\n']","[['3.8 l/100 km (comb)'], ['4.3 l/100 km (city...",['\n99 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air suspension', 'Armrest', 'Auxiliary heati...","['Bluetooth', 'CD player', 'Hands-free equipme...","['Alloy wheels', 'Sport seats', 'Voice Control']","['ABS', 'Alarm system', 'Central door lock wit...","['\nAudi A1: ', '- 1e eigenaar ', '- Perfecte ...",nan,['\n6\n'],nan,nan,nan,nan,nan,nan,nan
4,https://www.autoscout24.com//offers/audi-a1-sp...,Audi,Sportback 1.4 TDI S-Tronic S-Line Ext. admired...,Sedans,16790,None,16200 km,05/2016,1 previous owner,nan,66,"['', 'Used', '', 'Diesel (Particulate Filter)']",\n1\n,nan,"['\nYes\n', '\n109 g CO2/km (comb)\n']",6,"['\n', '\n', '\n4 (Green)\n']","['\n', '\n']",[],\nAudi\n,"['\n', 'A1', '\n']",1626,2016,Black,nMetallic,['\nMythosschwarz Metallic\n'],"['\nCloth, Black\n']","['\n', 'Sedans', '\n']",5,5,['\n0588/BDF\n'],"['\n', 'Automatic', '\n']","['\n1,422 cc\n']",['\n3\n'],nan,['\nfront\n'],"['\n', 'Diesel (Particulate Filter)', '\n']","[['4.1 l/100 km (comb)'], ['4.6 l/100 km (city...",['\n109 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air conditioning', 'Armrest', 'Automatic cli...","['Bluetooth', 'CD player', 'Hands-free equipme...","['Alloy wheels', 'Sport package', 'Sport suspe...","['ABS', 'Central door lock', 'Driver-side airb...","['\n', 'Technik & Sicherheit:', 'Xenon plus', ...",nan,nan,['\nGermany\n'],nan,nan,nan,nan,nan,nan

In [193]:
car1.tail()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous_Owners,Next_Inspection,Inspection_new,Warranty,Full_Service,Non-smoking_Vehicle,null,Make,Model,Offer_Number,First_Registration,Body_Color,Paint_Type,Body_Color_Original,Upholstery,Body,Nr._of_Doors,Nr._of_Seats,Model_Code,Gearing_Type,Displacement,Cylinders,Weight,Drive_chain,Fuel,Consumption,CO2_Emission,Emission_Class,\nComfort_&_Convenience\n,\nEntertainment_&_Media\n,\nExtras\n,\nSafety_&_Security\n,description,Emission_Label,Gears,Country_version,Electricity_consumption,Last_Service_Date,Other_Fuel_Types,Availability,Last_Timing_Belt_Service_Date,Available_from
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,deductible,- km,-/-,None,nan,147,"['', 'New', '', 'Diesel (Particulate Filter)']",nan,nan,nan,24,nan,nan,[],\nRenault\n,"['\n', 'Espace', '\n']",10988301,NaN,Grey,nMetallic,['\nGrigio scuro\n'],nan,"['\n', 'Van', '\n']",['\n5\n'],['\n5\n'],nan,"['\n', 'Automatic', '\n']","['\n1,997 cc\n']",['\n4\n'],"['\n1,758 kg\n']",['\nfront\n'],"['\n', 'Diesel (Particulate Filter)', '\n']","[['5.3 l/100 km (comb)'], ['6.2 l/100 km (city...",['\n139 g CO2/km (comb)\n'],nan,"['Air conditioning', 'Automatic climate contro...","['Bluetooth', 'Digital radio', 'Hands-free equ...","['Alloy wheels', 'Touch screen']","['ABS', 'Central door lock', 'Central door loc...",['\nVettura visionabile nella sede in Via Roma...,nan,['\n6\n'],nan,nan,nan,nan,nan,nan,nan
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,deductible,9900 km,01/2019,1 previous owner,nan,165,"['', 'Used', '', 'Super 95 / Super Plus 98 (Pa...","['\n1\n', '\n', '7.4 l/100 km (comb)', '\n', '...","['\n01/2022\n', '\n168 g CO2/km (comb)\n']",nan,6,nan,"['\n', '\n', '\n4 (Green)\n']",[],\nRenault\n,"['\n', 'Espace', '\n']",507370,2019,Grey,nMetallic,['\nStahl-Grau Metallic\n'],['\nCloth\n'],"['\n', 'Van', '\n']",['\n5\n'],['\n5\n'],['\n0000/000\n'],"['\n', 'Automatic', '\n']","['\n1,798 cc\n']",['\n4\n'],"['\n1,708 kg\n']",['\nfront\n'],"['\n', 'Super 95 / Super Plus 98 (Particulate ...","['\n', '7.4 l/100 km (comb)', '\n', '9.2 l/100...",['\n168 g CO2/km (comb)\n'],nan,"['Air conditioning', 'Automatic climate contro...","['Bluetooth', 'Digital radio', 'Hands-free equ...","['Alloy wheels', 'Touch screen', 'Voice Control']","['ABS', 'Adaptive Cruise Control', 'Blind spot...","['\nDach: Panorama-Glas-Schiebedach, Lackierun...",nan,['\n7\n'],['\nGermany\n'],nan,nan,"[[], [], []]",\nin 5 days from ordering\n,nan,nan
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,deductible,15 km,03/2019,1 previous owner,nan,146,"['', 'Pre-registered', '', 'Diesel']","['\n1\n', '\n139 g CO2/km (comb)\n']",nan,"['\nYes\n', '\nEuro 6d-TEMP\n']",4,"['\n', '\n']","['\n', '\n']",[],\nRenault\n,"['\n', 'Espace', '\n']",16,2019,White,nan,['\narktis-wei√ü\n'],"['\nFull leather, Black\n']","['\n', 'Van', '\n']",['\n5\n'],['\n7\n'],nan,"['\n', 'Automatic', '\n']","['\n1,997 cc\n']",['\n4\n'],nan,['\nfront\n'],"['\n', 'Diesel', '\n']","[['5.3 l/100 km (comb)'], ['6.2 l/100 km (city...",['\n139 g CO2/km (comb)\n'],['\nEuro 6d-TEMP\n'],"['Air conditioning', 'Armrest', 'Automatic cli...","['Bluetooth', 'Hands-free equipment', 'On-boar...",['Alloy wheels'],"['ABS', 'Adaptive Cruise Control', 'Blind spot...","['\n', 'Getriebe:', ' Automatik', 'Technik:', ...",nan,['\n6\n'],['\nAustria\n'],nan,nan,nan,\nin 120 days from ordering\n,nan,nan
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,deductible,10 km,06/2019,None,nan,147,"['', 'Pre-registered', '', 'Diesel']",nan,nan,nan,NaN,nan,nan,[],\nRenault\n,"['\n', 'Espace', '\n']",2691331,2019,Grey,nan,['\nGrigio\n'],['\nPart leather\n'],"['\n', 'Van', '\n']",['\n5\n'],['\n7\n'],nan,"['\n', 'Automatic', '\n']","['\n1,997 cc\n']",['\n4\n'],"['\n1,758 kg\n']",['\nfront\n'],"['\n', 'Diesel', '\n']","[['5.3 l/100 km (comb)'], ['6.2 l/100 km (city...",['\n139 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air conditioning', 'Automatic climate contro...","['Bluetooth', 'Digital radio', 'Radio', 'USB']","['Alloy wheels', 'Touch screen']","['ABS', 'Blind spot monitor', 'Driver-side air...","['\nDEK:[2691331]', 'Renault Espace Blue dCi 2...",nan,['\n6\n'],nan,nan,nan,nan,nan,nan,nan
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,deductible,- km,01/2019,1 previous owner,nan,165,"['', 'Demonstration', '', 'Super 95']",\n1\n,nan,"['\nYes\n', '\n153 g CO2/km (comb)\n']",NaN,nan,nan,[],\nRenault\n,"['\n', 'Espace', '\n']",30000008029,2019,Grey,nMetallic,['\nTitanium-Grau Metallic\n'],"['\nFull leather, Brown\n']","['\n', 'Van', '\n']",['\n5\n'],['\n5\n'],['\n3333/BHJ\n'],"['\n', 'Automatic', '\n']","['\n1,798 cc\n']",['\n4\n'],"['\n1,685 kg\n']",['\n4WD\n'],"['\n', 'Super 95', '\n']","[['6.8 l/100 km (comb)'], ['8.7 l/100 km (city...",['\n153 g CO2/km (comb)\n'],['\nEuro 6\n'],"['Air conditioning', 'Automatic climate contro...",['USB'],"['Alloy wheels', 'Touch screen']","['ABS', 'Blind spot monitor', 'Daytime running...","['\n', 'Sicherheit Airbags:', ' ', 'Seitenairb...",['\n4 (Green)\n'],nan,['\nGermany\n'],nan,nan,nan,nan,nan,nan

In [70]:
car1.tail()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous Owners,Next Inspection,Inspection new,Warranty,Full Service,Non-smoking Vehicle,null,Make,Model,Offer Number,First Registration,Body Color,Paint Type,Body Color Original,Upholstery,Body,Nr. of Doors,Nr. of Seats,Model Code,Gearing Type,Displacement,Cylinders,Weight,Drive chain,Fuel,Consumption,CO2 Emission,Emission Class,\nComfort & Convenience\n,\nEntertainment & Media\n,\nExtras\n,\nSafety & Security\n,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,147 kW,"[, New, , Diesel (Particulate Filter)]",NaN,NaN,NaN,\n24 months\n,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\n10988301\n],NaN,"[\n, Grey, \n]",[\nMetallic\n],[\nGrigio scuro\n],NaN,"[\n, Van, \n]",5,[\n5\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],"[\n1,758 kg\n]",[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],NaN,"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Hands-free equipmen...","[Alloy wheels, Touch screen]","[ABS, Central door lock, Central door lock wit...",[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,165 kW,"[, Used, , Super 95 / Super Plus 98 (Particula...","[\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...","[\n01/2022\n, \n168 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]",NaN,"[\n, \n, \n4 (Green)\n]",[],\nRenault\n,"[\n, Espace, \n]",[\n507370_3223\n],"[\n, 2019, \n]","[\n, Grey, \n]",[\nMetallic\n],[\nStahl-Grau Metallic\n],[\nCloth\n],"[\n, Van, \n]",5,[\n5\n],[\n0000/000\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,708 kg\n]",[\nfront\n],"[\n, Super 95 / Super Plus 98 (Particulate Fil...","[\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (ci...",[\n168 g CO2/km (comb)\n],NaN,"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Hands-free equipmen...","[Alloy wheels, Touch screen, Voice Control]","[ABS, Adaptive Cruise Control, Blind spot moni...","[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,146 kW,"[, Pre-registered, , Diesel]","[\n1\n, \n139 g CO2/km (comb)\n]",NaN,"[\nYes\n, \nEuro 6d-TEMP\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]","[\n, \n]",[],\nRenault\n,"[\n, Espace, \n]",[\nEspace16\n],"[\n, 2019, \n]","[\n, White, \n]",NaN,[\narktis-wei√ü\n],"[\nFull leather, Black\n]","[\n, Van, \n]",5,[\n7\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],NaN,[\nfront\n],"[\n, Diesel, \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, Hands-free equipment, On-board com...",[Alloy wheels],"[ABS, Adaptive Cruise Control, Blind spot moni...","[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,147 kW,"[, Pre-registered, , Diesel]",NaN,NaN,NaN,\n,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\n2691331\n],"[\n, 2019, \n]","[\n, Grey, \n]",NaN,[\nGrigio\n],[\nPart leather\n],"[\n, Van, \n]",5,[\n7\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],"[\n1,758 kg\n]",[\nfront\n],"[\n, Diesel, \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Radio, USB]","[Alloy wheels, Touch screen]","[ABS, Blind spot monitor, Driver-side airbag, ...","[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,165 kW,"[, Demonstration, , Super 95]",\n1\n,NaN,"[\nYes\n, \n153 g CO2/km (comb)\n]",NaN,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\nRe_30000008029\n],"[\n, 2019, \n]","[\n, Grey, \n]",[\nMetallic\n],[\nTitanium-Grau Metallic\n],"[\nFull leather, Brown\n]","[\n, Van, \n]",5,[\n5\n],[\n3333/BHJ\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,685 kg\n]",[\n4WD\n],"[\n, Super 95, \n]","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],...",[\n153 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...",[USB],"[Alloy wheels, Touch screen]","[ABS, Blind spot monitor, Daytime running ligh...","[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
car1[i]

In [88]:
car1.First_Registration=car1.First_Registration.str.extract(f'[\,](\W)')

In [49]:
car1.tail()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,hp,Type,Previous Owners,Next Inspection,Inspection new,Warranty,Full Service,Non-smoking Vehicle,null,Make,Model,Offer Number,First Registration,Body Color,Paint Type,Body Color Original,Upholstery,Body,Nr. of Doors,Nr. of Seats,Model Code,Gearing Type,Displacement,Cylinders,Weight,Drive chain,Fuel,Consumption,CO2 Emission,Emission Class,\nComfort & Convenience\n,\nEntertainment & Media\n,\nExtras\n,\nSafety & Security\n,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,147 kW,"[, New, , Diesel (Particulate Filter)]",NaN,NaN,NaN,\n24 months\n,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\n10988301\n],NaN,"[\n, Grey, \n]",[\nMetallic\n],[\nGrigio scuro\n],NaN,"[\n, Van, \n]",[\n5\n],[\n5\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],"[\n1,758 kg\n]",[\nfront\n],"[\n, Diesel (Particulate Filter), \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],NaN,"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Hands-free equipmen...","[Alloy wheels, Touch screen]","[ABS, Central door lock, Central door lock wit...",[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,165 kW,"[, Used, , Super 95 / Super Plus 98 (Particula...","[\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100...","[\n01/2022\n, \n168 g CO2/km (comb)\n]",NaN,"[\n, \n, \nEuro 6\n]",NaN,"[\n, \n, \n4 (Green)\n]",[],\nRenault\n,"[\n, Espace, \n]",[\n507370_3223\n],"[\n, 2019, \n]","[\n, Grey, \n]",[\nMetallic\n],[\nStahl-Grau Metallic\n],[\nCloth\n],"[\n, Van, \n]",[\n5\n],[\n5\n],[\n0000/000\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,708 kg\n]",[\nfront\n],"[\n, Super 95 / Super Plus 98 (Particulate Fil...","[\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (ci...",[\n168 g CO2/km (comb)\n],NaN,"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Hands-free equipmen...","[Alloy wheels, Touch screen, Voice Control]","[ABS, Adaptive Cruise Control, Blind spot moni...","[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,146 kW,"[, Pre-registered, , Diesel]","[\n1\n, \n139 g CO2/km (comb)\n]",NaN,"[\nYes\n, \nEuro 6d-TEMP\n]","[\n, \n, \n4 (Green)\n]","[\n, \n]","[\n, \n]",[],\nRenault\n,"[\n, Espace, \n]",[\nEspace16\n],"[\n, 2019, \n]","[\n, White, \n]",NaN,[\narktis-wei√ü\n],"[\nFull leather, Black\n]","[\n, Van, \n]",[\n5\n],[\n7\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],NaN,[\nfront\n],"[\n, Diesel, \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],[\nEuro 6d-TEMP\n],"[Air conditioning, Armrest, Automatic climate ...","[Bluetooth, Hands-free equipment, On-board com...",[Alloy wheels],"[ABS, Adaptive Cruise Control, Blind spot moni...","[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,147 kW,"[, Pre-registered, , Diesel]",NaN,NaN,NaN,\n,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\n2691331\n],"[\n, 2019, \n]","[\n, Grey, \n]",NaN,[\nGrigio\n],[\nPart leather\n],"[\n, Van, \n]",[\n5\n],[\n7\n],NaN,"[\n, Automatic, \n]","[\n1,997 cc\n]",[\n4\n],"[\n1,758 kg\n]",[\nfront\n],"[\n, Diesel, \n]","[[5.3 l/100 km (comb)], [6.2 l/100 km (city)],...",[\n139 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...","[Bluetooth, Digital radio, Radio, USB]","[Alloy wheels, Touch screen]","[ABS, Blind spot monitor, Driver-side airbag, ...","[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,165 kW,"[, Demonstration, , Super 95]",\n1\n,NaN,"[\nYes\n, \n153 g CO2/km (comb)\n]",NaN,NaN,NaN,[],\nRenault\n,"[\n, Espace, \n]",[\nRe_30000008029\n],"[\n, 2019, \n]","[\n, Grey, \n]",[\nMetallic\n],[\nTitanium-Grau Metallic\n],"[\nFull leather, Brown\n]","[\n, Van, \n]",[\n5\n],[\n5\n],[\n3333/BHJ\n],"[\n, Automatic, \n]","[\n1,798 cc\n]",[\n4\n],"[\n1,685 kg\n]",[\n4WD\n],"[\n, Super 95, \n]","[[6.8 l/100 km (comb)], [8.7 l/100 km (city)],...",[\n153 g CO2/km (comb)\n],[\nEuro 6\n],"[Air conditioning, Automatic climate control, ...",[USB],"[Alloy wheels, Touch screen]","[ABS, Blind spot monitor, Daytime running ligh...","[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
car1.iloc[1:1000,[4,6,7,8]]

     price      km registration prev_owner
1    14500   80000      03/2017       None
2    14640   83450      02/2016         1
3    14500   73000      08/2016         1
4    16790   16200      05/2016         1
5    15090   63668      02/2016         1
6    16422   62111      03/2016         1
7    14480   14986      02/2016         1
8    16700   57000      02/2016         1
9    17990   16103      06/2017       None
10   18500   11300      05/2018       None
11   17990   26415      05/2016         1
12   18380   31600      09/2016         1
13   18399   45764      06/2016       None
14   17990   34914      10/2016         1
15   18700   27000      04/2016         1
16   18900    9752      06/2018       None
17   18500   28408      11/2017         1
18   18400   50280      07/2016       None
19   18500   13406      05/2018       None
20   18500   51160      06/2017         1
21   18500   15850      03/2016         1
22   18900   17000      12/2016         1
23   18850    9077      05/2018       None
24   18500    3000      09/2018         1
25    8999  115000      05/2016       None
26   11444   84029      03/2016         1
27   11300   67800      06/2016         1
28   18900   14556      04/2018       None
29   11290   22000      03/2016       None
30   11290   38400      06/2016       None
31   11440   83307      05/2016         1
32   11445   39668      03/2016         1
33   11700   30353      08/2016         1
34   11900  126000      06/2016       None
35   11949   57500      01/2016         1
36   11890   73945      04/2016         1
37   11600   96000      07/2017         1
38   11900   43120      10/2016         2
39   11630  110715      01/2016         1
40   11880   31971      04/2016         1
41   11800   94800      02/2016         1
42   11850   85000      02/2016         1
43   11569  111265      03/2016         1
44   11490   44120      01/2016         1
45   11490   97976      06/2016         1
46   11500  106000      06/2016         1
47   11790   60000      06/2016       None
48   11490   58000      04/2016         2
49   11470   57454      10/2016         1
50   11480   94055      10/2016         1
51   11180   56000      06/2016         1
52   11450   27600      03/2016       None
53   11100  111670      06/2016       None
54   10900   30500      03/2016         1
55   10999   69500      02/2017         1
56   10900   43500      11/2016         1
57   10950   45696      04/2016         1
58   10800   34000      12/2016         2
59   10600   55000      06/2016       None
60   10800   99000      01/2016         1
61    9950  118500      05/2016         1
62   10300   85000      07/2016         1
63   10000  192000      05/2016         1
64   10490  130000      02/2016         1
65   18900   41294      11/2016       None
66   18900   64000      06/2017       None
67   18900   13135      01/2018       None
68   18900    4250      07/2017         1
69   18890    2949      09/2018         1
70   18890   17861      05/2017       None
71   18890   22800      03/2017         1
72   18880    5108      05/2017         1
73   18880   11335      04/2018         1
74   18880    6396      06/2018         1
75   18880   47800      01/2016         1
76   18880    7021      04/2018         1
77   18880   30952      04/2016         1
78   18880   33991      04/2016         1
79   18870   35800      04/2017         1
80   18850    7672      05/2018         1
81   18500   13406      05/2018       None
82   18870    8430      07/2018         1
83   18497   40488      03/2016         1
84   18490   24200      05/2017         2
85   18490   26500      01/2017       None
86   18490   58806      03/2016       None
87   18500   39000      03/2016         1
88   18490   16700      05/2017         1
89   18490   41900      04/2016         1
90   18480   15093      07/2016         1
91   18480    5211      02/2018         1
92   18470   12000      04/2018         2
93   18444   50066      02/2016         1
94   18400   51484      01/2017       None
95   18400   14770      05/2018       None
96   18900   12415      05/2018       None
97   18900   26064      05/2018       None
98   18900   16500      05/2018         1
99   18900    9000      06/2016         1
100  18900   12402      05/2018       None
101  18900   14702      05/2018       None
102  18900   14523      05/2018         1
103  18900    9082      05/2018       None
104  18900    9580      05/2018       None
105  18900   10013      06/2018       None
106  18900   10450      07/2018       None
107  18900   14878      05/2018       None
108  18900   10273      07/2018       None
109  18900   47500      10/2016       None
110  18900    9466      05/2018       None
111  18900   18971      05/2018       None
112  18900   31877      03/2018       None
113  18900    9878      06/2018       None
114  18900   17535      05/2018         1
115  18850   76264      10/2016       None
116  18850    6695      05/2018       None
117  18850   21275      05/2016         1
118  18850   12261      06/2018       None
119  18840    3620      07/2018         1
120  18800    8330      04/2018         1
121  18750   20306      09/2018         1
122  18730       1          -/-       None
123  18700   27000      04/2016         1
124  18690   31750      05/2016         1
125  18600   19800      06/2017         1
126  18500   52000      01/2016         1
127  18500   15500      02/2018         1
128  18620   25977      06/2016         1
129  18500    9000      08/2017         1
130  18500   65000      11/2017       None
131  18500   14493      05/2018       None
132  18500   33500      10/2017       None
133  18333    4800      08/2018         1
134  18350   51000      09/2016       None
135  18349    7307      06/2017         1
136  18333    4800      08/2018         1
137  18333    5500      08/2018         1
138  18300   35500      05/2018         1
139  18300   18000      02/2017         2
140  18290   40000      11/2017       None
141  18250   14551      05/2018       None
142  18200   16500      01/2018         1
143  18185   26700      03/2016         1
144  18150    8000      04/2017         2
145  18000   15000      05/2018         1
146  17998   14436      02/2017         2
147  17998   72624      03/2016         2
148  17990   13960      08/2016         1
149  17990   40301      04/2016         1
150  17990   19990      06/2017       None
151  17990    3087      09/2018         1
152  17989   37626      02/2016         1
153  17980   22980      11/2017         1
154  17980   57926      03/2016         1
155  17970    3900      06/2017         2
156  17980    7924      04/2016         1
157  17970    6257      11/2017         1
158  17950   29800      05/2016         1
159  17950   35816      03/2016       None
160  17950   12960      02/2018         1
161  17950    8600      08/2018         1
162  17950   14300      07/2017         2
163  17944    9463      03/2018         1
164  17940   20326      05/2016         1
165  17950   70000      05/2016         2
166  17500   23664      01/2018         2
167  17500   51900      02/2016         1
168  17500   15000      07/2017       None
169  17500   33000      11/2016         1
170  17450   12000      04/2016       None
171  17500   42000      04/2017       None
172  17930   25976      09/2017         1
173  17500   26299      02/2017       None
174  17495   40000      07/2017         2
175  17490   36530      03/2017         1
176  17490   29159      01/2017       None
177  17490   55000      05/2016         2
178  17449   40133      02/2016         1
179  17445   38562      02/2017         2
180  17444    7300      08/2018         1
181  17440   10457      10/2017         2
182  17420   27058      07/2016         1
183  17450   38344      11/2016         1
184  17445   45276      01/2016         1
185  17370   16607      04/2018         1
186  17350   26462      05/2016         1
187  17900   62000      06/2017         1
188  17930   40257      06/2017         1
189  17920   36709      06/2016         1
190  17900   25330      03/2017       None
191  17900   11300      11/2016       None
192  17900   10170      07/2018         1
193  17900   12260      05/2018         1
194  17900   44604      04/2016         1
195  17900   25751      02/2017       None
196  17900   13000      07/2017         1
197  17900   63136      07/2016       None
198  17900   21900      06/2017         1
199  17900   23357      09/2016         1
200  17900   40000      04/2016         2
201  17900   63136      07/2016       None
202  17890   27950      03/2016         1
203  16900    3150      03/2016         1
204  17900    4810      06/2018         1
205  16900   32700      11/2017       None
206  16900   67790      04/2016         2
207  17890   63500      02/2017         2
208  17900   37702      06/2017       None
209  17900   40164      11/2017         1
210  16900   47750      06/2016       None
211  16890   39600      03/2016         1
212  16890   29200      02/2016         1
213  16880   32103      02/2016         1
214  16880   19700      06/2017         1
215  16880    6680      12/2017         1
216  16880   49100      05/2016         1
217  16879   30348      04/2016         1
218  16870    7680      06/2017         1
219  16850   36400      06/2016       None
220  16840   49800      05/2016         2
221  16830   50200      02/2016         1
222  16876   47500      05/2016         1
223  16820   24762      01/2017         1
224  16800   36236      01/2016         1
225  16790   38831      04/2016         1
226  16780   18556      10/2017         1
227  16530   36625      04/2016       None
228  16500   25000      08/2016       None
229  16500   36041      04/2017       None
230  16500   36500      05/2016         1
231  16500   25000      08/2016       None
232  16500   66000      03/2016       None
233  16490   90000      01/2016       None
234  16490   14000      11/2016         1
235  16490   16081      03/2016         1
236  16480   32863      03/2016         1
237  16480   54889      05/2016         1
238  16450   18392      03/2016         1
239  16480   40800      05/2016         1
240  16480   60490      02/2016         1
241  16444   33142      12/2016         2
242  16430   40500      05/2016         2
243  16443   13819      04/2016         1
244  17300   18800      05/2016       None
245  17240   40550      06/2016         1
246  17150   25000      01/2016         1
247  17000   46000      03/2017       None
248  16999   31987      06/2017         1
249  16999   52800      06/2016         1
250  16995   57178      07/2016       None
251  16990   36500      10/2017         2
252  16990   14000      06/2017       None
253  16980   59500      04/2016       None
254  16970   26861      11/2016         1
255  16950   13200      01/2018         1
256  16975   19177      11/2017         2
257  16950   19044      05/2017         1
258  16930   40500      05/2016         1
259  16900   33000      03/2017         2
260  16900   21000      04/2017       None
261  16900   58033      03/2016       None
262  16900   32000      03/2017       None
263  17890   12500      04/2016         1
264  17890   36530      03/2017         1
265  17880    5991      03/2018         1
266  17880   33306      09/2017         1
267  17850   52896      05/2016         2
268  17750   32000      03/2017         1
269  17820    9998      07/2017         1
270  17790   49198      02/2016       None
271  17777   28600      02/2017         1
272  17820   59000      05/2017         1
273  17770   10300      05/2018         1
274  17700   24550      07/2017       None
275  17700   26000      04/2016       None
276  17700   40800      01/2016       None
277  17700   24550      06/2017         1
278  17660    7701      05/2018       None
279  17650   19500      04/2017         2
280  17650   45605      11/2017         1
281  17530   45200      04/2016         1
282  17500   22500      02/2017         2
283  15420   44585      04/2016         1
284  15250   32750      02/2016         1
285  15250   61980      03/2016         1
286  15190   37500      10/2017         1
287  15090   63668      02/2016         1
288  15200   49600      03/2016         1
289  15180   76275      01/2016         1
290  15380   46900      04/2016         1
291  15090   63668      02/2016         1
292  15090   63668      02/2016         1
293  15090   63668      02/2016         1
294  15090   63668      02/2016         1
295  15090   63668      02/2016         1
296  15090   63668      02/2016         1
297  15090   63668      02/2016         1
298  15090   63668      02/2016         1
299  14250   10000      10/2016         1
300  15090   63668      02/2016         1
301  14450   49466      02/2016         1
302  15090   63668      02/2016         1
303  14470   48800      03/2016         2
304  14350   94300      04/2016         1
305  14210   18600      05/2016         1
306  14300   67278      06/2016         1
307  13892   69850      12/2016         1
308  13990   46000      07/2016         1
309  13950   10000      09/2016       None
310  13900  108000      05/2016       None
311  15090   63668      02/2016         1
312  15090   63668      02/2016         1
313  15090   63668      02/2016         1
314  15090   63668      02/2016         1
315  15090   63668      02/2016         1
316  15090   63668      02/2016         1
317  15090   63668      02/2016         1
318  15090   63668      02/2016         1
319  15090   63668      02/2016         1
320  15090   63668      02/2016         1
321  15090   63668      02/2016         1
322  15090   63668      02/2016         1
323  14990   35367      04/2016         1
324  15090   63668      02/2016         1
325  15090   63668      02/2016         1
326  15090   63668      02/2016         1
327  15000   78000      03/2017       None
328  14998  137066      06/2016         1
329  14990   34000      03/2016         1
330  14990    9600      05/2017         1
331  13880   88800      06/2016       None
332  13500   59150      03/2016         1
333  13480  110375      04/2016         1
334  13450   26310      05/2018       None
335  13250   65000      04/2016         2
336  14990   49351      12/2016         2
337  14990   49351      12/2016         2
338  13599   58380      02/2016         1
339  14990   49351      12/2016         2
340  14990   49351      12/2016         2
341  14990   49351      12/2016         2
342  14990   49351      12/2016         2
343  14990   49351      12/2016         2
344  14990   49351      12/2016         2
345  14990   49351      12/2016         2
346  14990   49351      12/2016         2
347  15700   31100      03/2016         1
348  15680   79244      02/2016         1
349  14990   49351      12/2016         2
350  15750   58722      05/2016         1
351  14990   49351      12/2016         2
352  14990   49351      12/2016         2
353  15660   11725      05/2016         1
354  15750   41600      04/2016         2
355  11000   56000      03/2016       None
356  14990   49351      12/2016         2
357  14990   49351      12/2016         2
358  14990   49351      12/2016         2
359  14990   49351      12/2016         2
360  14990   49351      12/2016         2
361  14990   60000      01/2016       None
362  14990   49351      12/2016         2
363  14959   56967      03/2016         2
364  14959   56967      03/2016         2
365  14930   87300      07/2016         1
366  14930   86698      04/2016         2
367  14950   70000      01/2016       None
368  14930   87300      07/2016         1
369  14900  115900      05/2017         2
370  14850   25000      01/2016       None
371  14890   58718      05/2016         1
372  14700   35730      01/2016       None
373  14640   83450      02/2016         1
374  14799   75000      04/2016       None
375  14990   49351      12/2016         2
376  14990   49351      12/2016         2
377  14990   49351      12/2016         2
378  14990   49351      12/2016         2
379  14990   49351      12/2016         2
380  16395   58525      02/2016         1
381  16250   37000      12/2016       None
382  16400   42000      02/2016         1
383  14990   49351      12/2016         2
384  16290   53000      01/2016         2
385  14990   49351      12/2016         2
386  16199   31235      06/2016         2
387  15998   72761      06/2016       None
388  15990   73575      01/2016       None
389  16000   19000      03/2017         1
390  16150   19068      02/2017         1
391  16000   11000      04/2016         1
392  15993   33200      02/2016         1
393  15990   45000      09/2016         1
394  15990   42900      03/2016         1
395  15980   52900      01/2016         1
396  15590   40500      04/2016         1
397  15990  146140      01/2016       None
398  15980   44300      04/2016         2
399  15990    9300      03/2018         1
400  15980   72192      02/2016         1
401  15990   46123      03/2016         1
402  15580   18150      03/2017         1
403  15490   42979      04/2016         1
404  15500   24000      07/2016       None
405  15490   40528      06/2017       None
406  15500  104000      03/2016       None
407  15500   63473      07/2016       None
408  15490   29950      04/2016       None
409  15480   25320      01/2016         1
410  15450   24030      04/2017         1
411  15450   36590      04/2016         1
412  15450   34011      03/2016         1
413  15450   25600      03/2016         1
414  15444   13776      04/2016         1
415  15960   34400      04/2016         1
416  15960   34400      04/2016         1
417  15930   66844      03/2016         1
418  15900   58000      05/2016       None
419  15900   40000      04/2016       None
420  15900   41500      06/2016         1
421  15425   43255      04/2016         1
422  14990   49351      12/2016         2
423  15889   42023      12/2016         2
424  15970   36950      01/2016         1
425  15889  106829      06/2016         1
426  15880   49880      04/2017         2
427  15850   50272      10/2016       None
428  15850   69900      03/2016         1
429  15800   19582      09/2016         1
430  15790   43954      10/2016         1
431  15840   32910      03/2016         1
432  15830   23327      07/2016         1
433  15790   32814      02/2016         2
434  15789   59702      03/2016         1
435  15784   65838      03/2016       None
436  15780   23211      05/2016         1
437  12170   97930      03/2016         1
438  12490   70000      10/2016         1
439  12820   54392      01/2016         1
440  11950   73000      06/2016         1
441  12480  111380      04/2016         1
442  12480   63350      04/2016         1
443  12480  129550      02/2016         2
444  12900   28978      07/2016       None
445  13420   61220      01/2016         1
446  13490   71000      01/2017       None
447  13490   24999      04/2016       None
448  13490   46400      04/2016       None
449  12900   62400      02/2016         1
450  13680   81600      03/2016         1
451  13640   65500      09/2016         1
452  13650   25950      06/2016         1
453  13490   32779      05/2016         1
454  13660   75800      02/2016         1
455  13680   23450      04/2016         1
456  13750   63952      04/2016         1
457  13900   34000      09/2016       None
458  13900   47155      01/2016         1
459  13900   80000      03/2016       None
460  13900   39838      06/2016       None
461  13890   29600      03/2016       None
462  13890   30000      04/2016         1
463  13890   22223      05/2017         1
464  13890  107592      02/2016         1
465  13890  125000      04/2016         1
466  13900   20000      09/2017       None
467  13890   38900      05/2016         1
468  13890   18371      05/2017       None
469  13890   18371      05/2017       None
470  13890   18371      05/2017       None
471  13940   84708      04/2016         2
472  13940  115000      04/2016         1

In [53]:
car1.iloc[1:1000,[7,22]]

    registration First Registration
1        03/2017     [\n, 2017, \n]
2        02/2016     [\n, 2016, \n]
3        08/2016     [\n, 2016, \n]
4        05/2016     [\n, 2016, \n]
5        02/2016     [\n, 2016, \n]
6        03/2016     [\n, 2016, \n]
7        02/2016     [\n, 2016, \n]
8        02/2016     [\n, 2016, \n]
9        06/2017     [\n, 2017, \n]
10       05/2018     [\n, 2018, \n]
11       05/2016     [\n, 2016, \n]
12       09/2016     [\n, 2016, \n]
13       06/2016     [\n, 2016, \n]
14       10/2016     [\n, 2016, \n]
15       04/2016     [\n, 2016, \n]
16       06/2018     [\n, 2018, \n]
17       11/2017     [\n, 2017, \n]
18       07/2016     [\n, 2016, \n]
19       05/2018     [\n, 2018, \n]
20       06/2017     [\n, 2017, \n]
21       03/2016     [\n, 2016, \n]
22       12/2016     [\n, 2016, \n]
23       05/2018     [\n, 2018, \n]
24       09/2018     [\n, 2018, \n]
25       05/2016     [\n, 2016, \n]
26       03/2016     [\n, 2016, \n]
27       06/2016     [\n, 2016, \n]
28       04/2018     [\n, 2018, \n]
29       03/2016     [\n, 2016, \n]
30       06/2016     [\n, 2016, \n]
31       05/2016     [\n, 2016, \n]
32       03/2016     [\n, 2016, \n]
33       08/2016     [\n, 2016, \n]
34       06/2016     [\n, 2016, \n]
35       01/2016     [\n, 2016, \n]
36       04/2016     [\n, 2016, \n]
37       07/2017     [\n, 2017, \n]
38       10/2016     [\n, 2016, \n]
39       01/2016     [\n, 2016, \n]
40       04/2016     [\n, 2016, \n]
41       02/2016     [\n, 2016, \n]
42       02/2016     [\n, 2016, \n]
43       03/2016     [\n, 2016, \n]
44       01/2016     [\n, 2016, \n]
45       06/2016     [\n, 2016, \n]
46       06/2016     [\n, 2016, \n]
47       06/2016     [\n, 2016, \n]
48       04/2016     [\n, 2016, \n]
49       10/2016     [\n, 2016, \n]
50       10/2016     [\n, 2016, \n]
51       06/2016     [\n, 2016, \n]
52       03/2016     [\n, 2016, \n]
53       06/2016     [\n, 2016, \n]
54       03/2016     [\n, 2016, \n]
55       02/2017     [\n, 2017, \n]
56       11/2016     [\n, 2016, \n]
57       04/2016     [\n, 2016, \n]
58       12/2016     [\n, 2016, \n]
59       06/2016     [\n, 2016, \n]
60       01/2016     [\n, 2016, \n]
61       05/2016     [\n, 2016, \n]
62       07/2016     [\n, 2016, \n]
63       05/2016     [\n, 2016, \n]
64       02/2016     [\n, 2016, \n]
65       11/2016     [\n, 2016, \n]
66       06/2017     [\n, 2017, \n]
67       01/2018     [\n, 2018, \n]
68       07/2017     [\n, 2017, \n]
69       09/2018     [\n, 2018, \n]
70       05/2017     [\n, 2017, \n]
71       03/2017     [\n, 2017, \n]
72       05/2017     [\n, 2017, \n]
73       04/2018     [\n, 2018, \n]
74       06/2018     [\n, 2018, \n]
75       01/2016     [\n, 2016, \n]
76       04/2018     [\n, 2018, \n]
77       04/2016     [\n, 2016, \n]
78       04/2016     [\n, 2016, \n]
79       04/2017     [\n, 2017, \n]
80       05/2018     [\n, 2018, \n]
81       05/2018     [\n, 2018, \n]
82       07/2018     [\n, 2018, \n]
83       03/2016     [\n, 2016, \n]
84       05/2017     [\n, 2017, \n]
85       01/2017     [\n, 2017, \n]
86       03/2016     [\n, 2016, \n]
87       03/2016     [\n, 2016, \n]
88       05/2017     [\n, 2017, \n]
89       04/2016     [\n, 2016, \n]
90       07/2016     [\n, 2016, \n]
91       02/2018     [\n, 2018, \n]
92       04/2018     [\n, 2018, \n]
93       02/2016     [\n, 2016, \n]
94       01/2017     [\n, 2017, \n]
95       05/2018     [\n, 2018, \n]
96       05/2018     [\n, 2018, \n]
97       05/2018     [\n, 2018, \n]
98       05/2018     [\n, 2018, \n]
99       06/2016     [\n, 2016, \n]
100      05/2018     [\n, 2018, \n]
101      05/2018     [\n, 2018, \n]
102      05/2018     [\n, 2018, \n]
103      05/2018     [\n, 2018, \n]
104      05/2018     [\n, 2018, \n]
105      06/2018     [\n, 2018, \n]
106      07/2018     [\n, 2018, \n]
107      05/2018     [\n, 2018, \n]
108      07/2018     [\n, 2018, \n]
109      10/2016     [\n, 2016, \n]
110      05/2018     [\n, 2018, \n]
111      05/2018     [\n, 2018, \n]
112      03/2018     [\n, 2018, \n]
113      06/2018     [\n, 2018, \n]
114      05/2018     [\n, 2018, \n]
115      10/2016     [\n, 2016, \n]
116      05/2018     [\n, 2018, \n]
117      05/2016     [\n, 2016, \n]
118      06/2018     [\n, 2018, \n]
119      07/2018     [\n, 2018, \n]
120      04/2018     [\n, 2018, \n]
121      09/2018     [\n, 2018, \n]
122          -/-                NaN
123      04/2016     [\n, 2016, \n]
124      05/2016     [\n, 2016, \n]
125      06/2017     [\n, 2017, \n]
126      01/2016     [\n, 2016, \n]
127      02/2018     [\n, 2018, \n]
128      06/2016     [\n, 2016, \n]
129      08/2017     [\n, 2017, \n]
130      11/2017     [\n, 2017, \n]
131      05/2018     [\n, 2018, \n]
132      10/2017     [\n, 2017, \n]
133      08/2018     [\n, 2018, \n]
134      09/2016     [\n, 2016, \n]
135      06/2017     [\n, 2017, \n]
136      08/2018     [\n, 2018, \n]
137      08/2018     [\n, 2018, \n]
138      05/2018     [\n, 2018, \n]
139      02/2017     [\n, 2017, \n]
140      11/2017     [\n, 2017, \n]
141      05/2018     [\n, 2018, \n]
142      01/2018     [\n, 2018, \n]
143      03/2016     [\n, 2016, \n]
144      04/2017     [\n, 2017, \n]
145      05/2018     [\n, 2018, \n]
146      02/2017     [\n, 2017, \n]
147      03/2016     [\n, 2016, \n]
148      08/2016     [\n, 2016, \n]
149      04/2016     [\n, 2016, \n]
150      06/2017     [\n, 2017, \n]
151      09/2018     [\n, 2018, \n]
152      02/2016     [\n, 2016, \n]
153      11/2017     [\n, 2017, \n]
154      03/2016     [\n, 2016, \n]
155      06/2017     [\n, 2017, \n]
156      04/2016     [\n, 2016, \n]
157      11/2017     [\n, 2017, \n]
158      05/2016     [\n, 2016, \n]
159      03/2016     [\n, 2016, \n]
160      02/2018     [\n, 2018, \n]
161      08/2018     [\n, 2018, \n]
162      07/2017     [\n, 2017, \n]
163      03/2018     [\n, 2018, \n]
164      05/2016     [\n, 2016, \n]
165      05/2016     [\n, 2016, \n]
166      01/2018     [\n, 2018, \n]
167      02/2016     [\n, 2016, \n]
168      07/2017     [\n, 2017, \n]
169      11/2016     [\n, 2016, \n]
170      04/2016     [\n, 2016, \n]
171      04/2017     [\n, 2017, \n]
172      09/2017     [\n, 2017, \n]
173      02/2017     [\n, 2017, \n]
174      07/2017     [\n, 2017, \n]
175      03/2017     [\n, 2017, \n]
176      01/2017     [\n, 2017, \n]
177      05/2016     [\n, 2016, \n]
178      02/2016     [\n, 2016, \n]
179      02/2017     [\n, 2017, \n]
180      08/2018     [\n, 2018, \n]
181      10/2017     [\n, 2017, \n]
182      07/2016     [\n, 2016, \n]
183      11/2016     [\n, 2016, \n]
184      01/2016     [\n, 2016, \n]
185      04/2018     [\n, 2018, \n]
186      05/2016     [\n, 2016, \n]
187      06/2017     [\n, 2017, \n]
188      06/2017     [\n, 2017, \n]
189      06/2016     [\n, 2016, \n]
190      03/2017     [\n, 2017, \n]
191      11/2016     [\n, 2016, \n]
192      07/2018     [\n, 2018, \n]
193      05/2018     [\n, 2018, \n]
194      04/2016     [\n, 2016, \n]
195      02/2017     [\n, 2017, \n]
196      07/2017     [\n, 2017, \n]
197      07/2016     [\n, 2016, \n]
198      06/2017     [\n, 2017, \n]
199      09/2016     [\n, 2016, \n]
200      04/2016     [\n, 2016, \n]
201      07/2016     [\n, 2016, \n]
202      03/2016     [\n, 2016, \n]
203      03/2016     [\n, 2016, \n]
204      06/2018     [\n, 2018, \n]
205      11/2017     [\n, 2017, \n]
206      04/2016     [\n, 2016, \n]
207      02/2017     [\n, 2017, \n]
208      06/2017     [\n, 2017, \n]
209      11/2017     [\n, 2017, \n]
210      06/2016     [\n, 2016, \n]
211      03/2016     [\n, 2016, \n]
212      02/2016     [\n, 2016, \n]
213      02/2016     [\n, 2016, \n]
214      06/2017     [\n, 2017, \n]
215      12/2017     [\n, 2017, \n]
216      05/2016     [\n, 2016, \n]
217      04/2016     [\n, 2016, \n]
218      06/2017     [\n, 2017, \n]
219      06/2016     [\n, 2016, \n]
220      05/2016     [\n, 2016, \n]
221      02/2016     [\n, 2016, \n]
222      05/2016     [\n, 2016, \n]
223      01/2017     [\n, 2017, \n]
224      01/2016     [\n, 2016, \n]
225      04/2016     [\n, 2016, \n]
226      10/2017     [\n, 2017, \n]
227      04/2016     [\n, 2016, \n]
228      08/2016     [\n, 2016, \n]
229      04/2017     [\n, 2017, \n]
230      05/2016     [\n, 2016, \n]
231      08/2016     [\n, 2016, \n]
232      03/2016     [\n, 2016, \n]
233      01/2016     [\n, 2016, \n]
234      11/2016     [\n, 2016, \n]
235      03/2016     [\n, 2016, \n]
236      03/2016     [\n, 2016, \n]
237      05/2016     [\n, 2016, \n]
238      03/2016     [\n, 2016, \n]
239      05/2016     [\n, 2016, \n]
240      02/2016     [\n, 2016, \n]
241      12/2016     [\n, 2016, \n]
242      05/2016     [\n, 2016, \n]
243      04/2016     [\n, 2016, \n]
244      05/2016     [\n, 2016, \n]
245      06/2016     [\n, 2016, \n]
246      01/2016     [\n, 2016, \n]
247      03/2017     [\n, 2017, \n]
248      06/2017     [\n, 2017, \n]
249      06/2016     [\n, 2016, \n]
250      07/2016     [\n, 2016, \n]
251      10/2017     [\n, 2017, \n]
252      06/2017     [\n, 2017, \n]
253      04/2016     [\n, 2016, \n]
254      11/2016     [\n, 2016, \n]
255      01/2018     [\n, 2018, \n]
256      11/2017     [\n, 2017, \n]
257      05/2017     [\n, 2017, \n]
258      05/2016     [\n, 2016, \n]
259      03/2017     [\n, 2017, \n]
260      04/2017     [\n, 2017, \n]
261      03/2016     [\n, 2016, \n]
262      03/2017     [\n, 2017, \n]
263      04/2016     [\n, 2016, \n]
264      03/2017     [\n, 2017, \n]
265      03/2018     [\n, 2018, \n]
266      09/2017     [\n, 2017, \n]
267      05/2016     [\n, 2016, \n]
268      03/2017     [\n, 2017, \n]
269      07/2017     [\n, 2017, \n]
270      02/2016     [\n, 2016, \n]
271      02/2017     [\n, 2017, \n]
272      05/2017     [\n, 2017, \n]
273      05/2018     [\n, 2018, \n]
274      07/2017     [\n, 2017, \n]
275      04/2016     [\n, 2016, \n]
276      01/2016     [\n, 2016, \n]
277      06/2017     [\n, 2017, \n]
278      05/2018     [\n, 2018, \n]
279      04/2017     [\n, 2017, \n]
280      11/2017     [\n, 2017, \n]
281      04/2016     [\n, 2016, \n]
282      02/2017     [\n, 2017, \n]
283      04/2016     [\n, 2016, \n]
284      02/2016     [\n, 2016, \n]
285      03/2016     [\n, 2016, \n]
286      10/2017     [\n, 2017, \n]
287      02/2016     [\n, 2016, \n]
288      03/2016     [\n, 2016, \n]
289      01/2016     [\n, 2016, \n]
290      04/2016     [\n, 2016, \n]
291      02/2016     [\n, 2016, \n]
292      02/2016     [\n, 2016, \n]
293      02/2016     [\n, 2016, \n]
294      02/2016     [\n, 2016, \n]
295      02/2016     [\n, 2016, \n]
296      02/2016     [\n, 2016, \n]
297      02/2016     [\n, 2016, \n]
298      02/2016     [\n, 2016, \n]
299      10/2016     [\n, 2016, \n]
300      02/2016     [\n, 2016, \n]
301      02/2016     [\n, 2016, \n]
302      02/2016     [\n, 2016, \n]
303      03/2016     [\n, 2016, \n]
304      04/2016     [\n, 2016, \n]
305      05/2016     [\n, 2016, \n]
306      06/2016     [\n, 2016, \n]
307      12/2016     [\n, 2016, \n]
308      07/2016     [\n, 2016, \n]
309      09/2016     [\n, 2016, \n]
310      05/2016     [\n, 2016, \n]
311      02/2016     [\n, 2016, \n]
312      02/2016     [\n, 2016, \n]
313      02/2016     [\n, 2016, \n]
314      02/2016     [\n, 2016, \n]
315      02/2016     [\n, 2016, \n]
316      02/2016     [\n, 2016, \n]
317      02/2016     [\n, 2016, \n]
318      02/2016     [\n, 2016, \n]
319      02/2016     [\n, 2016, \n]
320      02/2016     [\n, 2016, \n]
321      02/2016     [\n, 2016, \n]
322      02/2016     [\n, 2016, \n]
323      04/2016     [\n, 2016, \n]
324      02/2016     [\n, 2016, \n]
325      02/2016     [\n, 2016, \n]
326      02/2016     [\n, 2016, \n]
327      03/2017     [\n, 2017, \n]
328      06/2016     [\n, 2016, \n]
329      03/2016     [\n, 2016, \n]
330      05/2017     [\n, 2017, \n]
331      06/2016     [\n, 2016, \n]
332      03/2016     [\n, 2016, \n]
333      04/2016     [\n, 2016, \n]
334      05/2018     [\n, 2018, \n]
335      04/2016     [\n, 2016, \n]
336      12/2016     [\n, 2016, \n]
337      12/2016     [\n, 2016, \n]
338      02/2016     [\n, 2016, \n]
339      12/2016     [\n, 2016, \n]
340      12/2016     [\n, 2016, \n]
341      12/2016     [\n, 2016, \n]
342      12/2016     [\n, 2016, \n]
343      12/2016     [\n, 2016, \n]
344      12/2016     [\n, 2016, \n]
345      12/2016     [\n, 2016, \n]
346      12/2016     [\n, 2016, \n]
347      03/2016     [\n, 2016, \n]
348      02/2016     [\n, 2016, \n]
349      12/2016     [\n, 2016, \n]
350      05/2016     [\n, 2016, \n]
351      12/2016     [\n, 2016, \n]
352      12/2016     [\n, 2016, \n]
353      05/2016     [\n, 2016, \n]
354      04/2016     [\n, 2016, \n]
355      03/2016     [\n, 2016, \n]
356      12/2016     [\n, 2016, \n]
357      12/2016     [\n, 2016, \n]
358      12/2016     [\n, 2016, \n]
359      12/2016     [\n, 2016, \n]
360      12/2016     [\n, 2016, \n]
361      01/2016     [\n, 2016, \n]
362      12/2016     [\n, 2016, \n]
363      03/2016     [\n, 2016, \n]
364      03/2016     [\n, 2016, \n]
365      07/2016     [\n, 2016, \n]
366      04/2016     [\n, 2016, \n]
367      01/2016     [\n, 2016, \n]
368      07/2016     [\n, 2016, \n]
369      05/2017     [\n, 2017, \n]
370      01/2016     [\n, 2016, \n]
371      05/2016     [\n, 2016, \n]
372      01/2016     [\n, 2016, \n]
373      02/2016     [\n, 2016, \n]
374      04/2016     [\n, 2016, \n]
375      12/2016     [\n, 2016, \n]
376      12/2016     [\n, 2016, \n]
377      12/2016     [\n, 2016, \n]
378      12/2016     [\n, 2016, \n]
379      12/2016     [\n, 2016, \n]
380      02/2016     [\n, 2016, \n]
381      12/2016     [\n, 2016, \n]
382      02/2016     [\n, 2016, \n]
383      12/2016     [\n, 2016, \n]
384      01/2016     [\n, 2016, \n]
385      12/2016     [\n, 2016, \n]
386      06/2016     [\n, 2016, \n]
387      06/2016     [\n, 2016, \n]
388      01/2016     [\n, 2016, \n]
389      03/2017     [\n, 2017, \n]
390      02/2017     [\n, 2017, \n]
391      04/2016     [\n, 2016, \n]
392      02/2016     [\n, 2016, \n]
393      09/2016     [\n, 2016, \n]
394      03/2016     [\n, 2016, \n]
395      01/2016     [\n, 2016, \n]
396      04/2016     [\n, 2016, \n]
397      01/2016     [\n, 2016, \n]
398      04/2016     [\n, 2016, \n]
399      03/2018     [\n, 2018, \n]
400      02/2016     [\n, 2016, \n]
401      03/2016     [\n, 2016, \n]
402      03/2017     [\n, 2017, \n]
403      04/2016     [\n, 2016, \n]
404      07/2016     [\n, 2016, \n]
405      06/2017     [\n, 2017, \n]
406      03/2016     [\n, 2016, \n]
407      07/2016     [\n, 2016, \n]
408      04/2016     [\n, 2016, \n]
409      01/2016     [\n, 2016, \n]
410      04/2017     [\n, 2017, \n]
411      04/2016     [\n, 2016, \n]
412      03/2016     [\n, 2016, \n]
413      03/2016     [\n, 2016, \n]
414      04/2016     [\n, 2016, \n]
415      04/2016     [\n, 2016, \n]
416      04/2016     [\n, 2016, \n]
417      03/2016     [\n, 2016, \n]
418      05/2016     [\n, 2016, \n]
419      04/2016     [\n, 2016, \n]
420      06/2016     [\n, 2016, \n]
421      04/2016     [\n, 2016, \n]
422      12/2016     [\n, 2016, \n]
423      12/2016     [\n, 2016, \n]
424      01/2016     [\n, 2016, \n]
425      06/2016     [\n, 2016, \n]
426      04/2017     [\n, 2017, \n]
427      10/2016     [\n, 2016, \n]
428      03/2016     [\n, 2016, \n]
429      09/2016     [\n, 2016, \n]
430      10/2016     [\n, 2016, \n]
431      03/2016     [\n, 2016, \n]
432      07/2016     [\n, 2016, \n]
433      02/2016     [\n, 2016, \n]
434      03/2016     [\n, 2016, \n]
435      03/2016     [\n, 2016, \n]
436      05/2016     [\n, 2016, \n]
437      03/2016     [\n, 2016, \n]
438      10/2016     [\n, 2016, \n]
439      01/2016     [\n, 2016, \n]
440      06/2016     [\n, 2016, \n]
441      04/2016     [\n, 2016, \n]
442      04/2016     [\n, 2016, \n]
443      02/2016     [\n, 2016, \n]
444      07/2016     [\n, 2016, \n]
445      01/2016     [\n, 2016, \n]
446      01/2017     [\n, 2017, \n]
447      04/2016     [\n, 2016, \n]
448      04/2016     [\n, 2016, \n]
449      02/2016     [\n, 2016, \n]
450      03/2016     [\n, 2016, \n]
451      09/2016     [\n, 2016, \n]
452      06/2016     [\n, 2016, \n]
453      05/2016     [\n, 2016, \n]
454      02/2016     [\n, 2016, \n]
455      04/2016     [\n, 2016, \n]
456      04/2016     [\n, 2016, \n]
457      09/2016     [\n, 2016, \n]
458      01/2016     [\n, 2016, \n]
459      03/2016     [\n, 2016, \n]
460      06/2016     [\n, 2016, \n]
461      03/2016     [\n, 2016, \n]
462      04/2016     [\n, 2016, \n]
463      05/2017     [\n, 2017, \n]
464      02/2016     [\n, 2016, \n]
465      04/2016     [\n, 2016, \n]
466      09/2017     [\n, 2017, \n]
467      05/2016     [\n, 2016, \n]
468      05/2017     [\n, 2017, \n]
469      05/2017     [\n, 2017, \n]
470      05/2017     [\n, 2017, \n]
471      04/2016     [\n, 2016, \n]
472      04/2016     [\n, 2016, \n]
473      03/2016     [\n, 2016, \n]
474      10/2016     [\n, 2016, \n]
475      05/2016     [\n, 2016, \n]
476      03/2016     [\n, 2016, \n]
477      02/2016     [\n, 2016, \n]
478      04/2016     [\n, 2016, \n]
479      11/2017     [\n, 2017, \n]
480      02/2016     [\n, 2016, \n]
481      06/2016     [\n, 2016, \n]
482      02/2016     [\n, 2016, \n]
483      01/2016     [\n, 2016, \n]
484      03/2016     [\n, 2016, \n]
485      08/2016     [\n, 2016, \n]
486      03/2016     [\n, 2016, \n]
487      08/2016     [\n, 2016, \n]
488      10/2016     [\n, 2016, \n]
489      04/2016     [\n, 2016, \n]
490      03/2016     [\n, 2016, \n]
491      03/2016     [\n, 2016, \n]
492      03/2016     [\n, 2016, \n]
493      03/2016     [\n, 2016, \n]
494      03/2016     [\n, 2016, \n]
495      03/2016     [\n, 2016, \n]
496      04/2016     [\n, 2016, \n]
497      10/2016     [\n, 2016, \n]
498      01/2016     [\n, 2016, \n]
499      04/2016     [\n, 2016, \n]
500      03/2016     [\n, 2016, \n]
501      08/2016     [\n, 2016, \n]
502      04/2016     [\n, 2016, \n]
503      03/2016     [\n, 2016, \n]
504      03/2016     [\n, 2016, \n]
505      06/2016     [\n, 2016, \n]
506      11/2016     [\n, 2016, \n]
507      10/2016     [\n, 2016, \n]
508      01/2016     [\n, 2016, \n]
509      04/2016     [\n, 2016, \n]
510      01/2016     [\n, 2016, \n]
511      02/2016     [\n, 2016, \n]
512      02/2016     [\n, 2016, \n]
513      09/2016     [\n, 2016, \n]
514      05/2016     [\n, 2016, \n]
515      06/2016     [\n, 2016, \n]
516      04/2016     [\n, 2016, \n]
517      07/2016     [\n, 2016, \n]
518      07/2016     [\n, 2016, \n]
519      03/2016     [\n, 2016, \n]
520      08/2016     [\n, 2016, \n]
521      04/2016     [\n, 2016, \n]
522      09/2016     [\n, 2016, \n]
523      09/2016     [\n, 2016, \n]
524      10/2016     [\n, 2016, \n]
525      05/2016     [\n, 2016, \n]
526      05/2016     [\n, 2016, \n]
527      02/2016     [\n, 2016, \n]
528      03/2016     [\n, 2016, \n]
529      02/2016     [\n, 2016, \n]
530      03/2016     [\n, 2016, \n]
531      03/2016     [\n, 2016, \n]
532      03/2016     [\n, 2016, \n]
533      02/2016     [\n, 2016, \n]
534      06/2016     [\n, 2016, \n]
535      02/2016     [\n, 2016, \n]
536      02/2016     [\n, 2016, \n]
537      12/2016     [\n, 2016, \n]
538      03/2016     [\n, 2016, \n]
539      04/2016     [\n, 2016, \n]
540      04/2016     [\n, 2016, \n]
541      04/2016     [\n, 2016, \n]
542      04/2016     [\n, 2016, \n]
543      04/2016     [\n, 2016, \n]
544      02/2016     [\n, 2016, \n]
545      06/2016     [\n, 2016, \n]
546      02/2016     [\n, 2016, \n]
547      02/2016     [\n, 2016, \n]
548      11/2016     [\n, 2016, \n]
549      02/2016     [\n, 2016, \n]
550      05/2016     [\n, 2016, \n]
551      02/2016     [\n, 2016, \n]
552      05/2016     [\n, 2016, \n]
553      02/2016     [\n, 2016, \n]
554      03/2016     [\n, 2016, \n]

In [52]:
pd.get_dummies(car1.iloc[1:500,23:25],columns=["prev_owner"])

KeyError: "None of [Index(['prev_owner'], dtype='object')] are in the [columns]"

In [116]:
car1new = car1[["make_model","price"]]

In [106]:
car1new = pd.DataFrame(car1.make_model)

In [117]:
car1new.head()

  make_model  price
0    Audi A1  15770
1    Audi A1  14500
2    Audi A1  14640
3    Audi A1  14500
4    Audi A1  16790

In [7]:
car.tail()

,url,make_model,short_description,body_type,price,vat,km,registration,prev_owner,kW,...,description,Emission Label,Gears,Country version,Electricity consumption,Last Service Date,Other Fuel Types,Availability,Last Timing Belt Service Date,Available from
15914,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200CV EDC Executive 4Control,Van,39950,VAT deductible,- km,-/-,None,NaN,...,[\nVettura visionabile nella sede in Via Roma ...,NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15915,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"TCe 225 EDC GPF LIM Deluxe Pano,RFK",Van,39885,VAT deductible,"9,900 km",01/2019,1 previous owner,NaN,...,"[\nDach: Panorama-Glas-Schiebedach, Lackierung...",NaN,[\n7\n],[\nGermany\n],NaN,NaN,"[[], [], []]",\nin 5 days from ordering\n,NaN,NaN
15916,https://www.autoscout24.com//offers/renault-es...,Renault Espace,Blue dCi 200 EDC Initiale Paris Leder LED Navi...,Van,39875,VAT deductible,15 km,03/2019,1 previous owner,NaN,...,"[\n, Getriebe:, Automatik, Technik:, Bordcom...",NaN,[\n6\n],[\nAustria\n],NaN,NaN,NaN,\nin 120 days from ordering\n,NaN,NaN
15917,https://www.autoscout24.com//offers/renault-es...,Renault Espace,"Blue dCi 200CV EDC Business , NUOVA DA IMMATRI...",Van,39700,VAT deductible,10 km,06/2019,None,NaN,...,"[\nDEK:[2691331], Renault Espace Blue dCi 200C...",NaN,[\n6\n],NaN,NaN,NaN,NaN,NaN,NaN,NaN
15918,https://www.autoscout24.com//offers/renault-es...,Renault Espace,INITIALE PARIS TCe 225 EDC GPF NAVI SHZ AUX,Van,40999,VAT deductible,- km,01/2019,1 previous owner,NaN,...,"[\n, Sicherheit Airbags:, , Seitenairbag, , ...",[\n4 (Green)\n],NaN,[\nGermany\n],NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
car.columns

Index(['url', 'make_model', 'short_description', 'body_type', 'price', 'vat',
       'km', 'registration', 'prev_owner', 'kW', 'hp', 'Type',
       'Previous Owners', 'Next Inspection', 'Inspection new', 'Warranty',
       'Full Service', 'Non-smoking Vehicle', 'null', 'Make', 'Model',
       'Offer Number', 'First Registration', 'Body Color', 'Paint Type',
       'Body Color Original', 'Upholstery', 'Body', 'Nr. of Doors',
       'Nr. of Seats', 'Model Code', 'Gearing Type', 'Displacement',
       'Cylinders', 'Weight', 'Drive chain', 'Fuel', 'Consumption',
       'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n',
       '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n',
       'description', 'Emission Label', 'Gears', 'Country version',
       'Electricity consumption', 'Last Service Date', 'Other Fuel Types',
       'Availability', 'Last Timing Belt Service Date', 'Available from'],
      dtype='object')

In [9]:
car.describe()

              price   kW
count  15919.000000  0.0
mean   18019.896727  NaN
std     7386.169409  NaN
min       13.000000  NaN
25%    12850.000000  NaN
50%    16900.000000  NaN
75%    21900.000000  NaN
max    74600.000000  NaN

In [10]:
car.isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
kW                               15919
hp                                   0
Type                                 2
Previous Owners                   6640
Next Inspection                  12384
Inspection new                   11987
Warranty                          5420
Full Service                      7704
Non-smoking Vehicle               8742
null                                 0
Make                                 0
Model                                0
Offer Number                      3175
First Registration                1597
Body Color                         597
Paint Type                        5772
Body Color Original               3759
Upholstery                        3720
Body                                60
Nr. of Doors                       212
Nr. of Seats                       977
Model Code                       10941
Gearing Type                         0
Displacement                       496
Cylinders                         5680
Weight                            6974
Drive chain                       6858
Fuel                                 0
Consumption                       1906
CO2 Emission                      1808
Emission Class                    3021
\nComfort & Convenience\n          920
\nEntertainment & Media\n         1374
\nExtras\n                        2962
\nSafety & Security\n              982
description                          0
Emission Label                   11934
Gears                             4712
Country version                   8333
Electricity consumption          15782
Last Service Date                15353
Other Fuel Types                 15039
Availability                     15284
Last Timing Belt Service Date    15903
Available from                   15647
dtype: int64